---
# tasks file for vmx

- name: Create user 
  user:
      name: "{{ user_for_ansible }}"
      shell: /bin/bash
  tags: usr

- name: Create directory for ssh key
  file: 
    path: "/home/{{ user_for_ansible }}/.ssh"
    mode: 0600
    owner: "{{ user_for_ansible }}"
    group: "{{ user_for_ansible }}"
    state: directory
  tags: keys
  
- name: create authorized_keys
  copy:
    src: "files/id_rsa.pub"
    dest: "/home/{{ user_for_ansible }}/.ssh/authorized_keys"
  tags: keys